Drilling and condition first iteration
MindPort-GmbH/VIRTOSHA-VR-Builder pull request #1
Opened 2024-07-30 13:11 UTC by VaLiuM09

Note: A clear description of this PR can be found in the documentation.

- Prototype components to assemble a usable drill: Drill, DrillBit, DrillTip - Drill should be on the interactable object, DrillBit at the base of the bit, DrillTip aligned to DrillBit at the tip of the drill, with a small trigger collider.
- Drillable property for defining drillable objects.
- Drillable Socket property for outlining where holes should be drilled.
- DrillHolesCondition that checks if a given object has holes drilled at specific positions (defined by drillable sockets).

## Greptile Summary

The pull request introduces a new drilling feature with several components and conditions for checking drilled holes.

- Added `Source/Editor/MenuItems/DrillHolesConditionMenuItem.cs` to create a new DrillHolesCondition menu item.
- Implemented `Source/Runtime/Components/Drill.cs` for handling the drilling process and interactions.
- Introduced `Source/Runtime/Components/DrillBit.cs` and `Source/Runtime/Components/DrillTip.cs` for defining drill bit and tip behavior.
- Added `Source/Runtime/Components/DebugDrillingAffordance.cs` and `Source/Runtime/Components/DebugHoleRepresentation.cs` for visualizing drilling operations.
- Comprehensive documentation added in `Documentation/virtosha-manual.md` detailing setup and usage.

2024-08-10 06:52 UTC, mrwellmann commented on Source/Runtime/Components/DrillTip.cs
> +                Debug.LogError($"No collider is set on {typeof(DrillTip).Name} on '{gameObject.name}'. A collider is needed for the component to work as intended. Please add one.");
```suggestion
                Debug.LogError($"No collider is set on {typeof(DrillTip).Name} on '{gameObject.name}'. A collider is needed for the component to work as intended. Please add one and set Is Trigger to true in the inspector.");
```

2024-08-10 08:46 UTC, mrwellmann requested changes
Overall great stuff would not have made it better.

You could add some test for wrongly set up components e.g.: DrillTip without trigger ...

2024-08-10 08:46 UTC, mrwellmann commented on Source/Runtime/Properties/DrillableProperty.cs
> +            );
```suggestion
			// Small epsilon value for floating-point comparison
			float epsilon = 0.0001f;

            return holes.Any(hole =>
            {
                // Calculate distances
                float enterDistance = Vector3.Distance(transform.TransformPoint(hole.EnterPoint), enterPosition);
                float endDistance = Vector3.Distance(transform.TransformPoint(hole.EndPoint), endPosition);
                float widthDifference = Mathf.Abs(hole.Width - width);

                // Check if distances are within tolerances
                bool isEnterWithinTolerance = Mathf.Abs(enterDistance - startTolerance) <= epsilon;
                bool isEndWithinTolerance = Mathf.Abs(endDistance - endTolerance) <= epsilon;
                bool isWidthWithinTolerance = widthDifference <= widthTolerance + epsilon;

                // Return true if all conditions are met
                return isEnterWithinTolerance && isEndWithinTolerance && isWidthWithinTolerance;
            });
```

2024-08-10 08:46 UTC, mrwellmann commented on Source/Runtime/Properties/DrillableSocketProperty.cs
> +        public void Configure(Hole hole, float enterTolerance = 0.01F, float endTolerance = 0.01F, float widthTolerance = 0.001F, bool placeEnterPointOnSurface = true)
```suggestion
        public void Configure(Hole hole, float enterTolerance = 0.01f, float endTolerance = 0.01f, float widthTolerance = 0.001f, bool placeEnterPointOnSurface = true)
```

2024-08-10 08:46 UTC, mrwellmann commented on Source/Runtime/Properties/DrillableSocketProperty.cs
> +                endPoint.transform.position = transform.position + new Vector3(0, -0.1f, 0);
please explain -0.1f as comment or variable

2024-08-10 08:46 UTC, mrwellmann commented on Tests/DrillHolesConditionTests.cs
> +        public IEnumerator ConditionIsFulfilled(Hole expected, Hole actual)
Note: This test failed for me the first time I run it. Following test runs where true.

ConditionIsFulfilled([(10.00, 12.00, 10.00)-(10.00, 10.20, 10.00)W0,2],[(10.00, 10.50, 10.00)-(10.00, 10.20, 10.00)W0,2]) (0,146s)
---
Expected: True
  But was:  False
---

2024-08-12 09:38 UTC, VaLiuM09 commented on Source/Runtime/Properties/DrillableProperty.cs
> +            );
No need to add as there are tolerances already

2024-08-12 09:45 UTC, VaLiuM09 commented on Source/Runtime/Properties/DrillableSocketProperty.cs
> +                endPoint.transform.position = transform.position + new Vector3(0, -0.1f, 0);
I don't think it's necessary, it's just a default value so the two points don't overlap

2024-08-12 09:50 UTC, VaLiuM09 commented on Source/Runtime/Components/DrillTip.cs
> +}
Do you think it's necessary to let the user manually assign the collider to the drill tip? I feel it can make everything clunkier, tbh I can't think of a situation where you wouldn't just add a child object with a drill tip and a sphere collider. If anything, I could consider adding a [RequireComponent(typeof(SphereCollider))] instead, but then I would also have to automatically size it to a default small value (which shouldn't be that much of a problem anyway).

2024-08-12 12:52 UTC, VaLiuM09 commented on Tests/DrillHolesConditionTests.cs
> +        public IEnumerator ConditionIsFulfilled(Hole expected, Hole actual)
Probably because that test used a socket which projected the enter point on the object's surface. I added a WaitForFixedUpdate to ensure it has time to raycast and the test seems to succeed consistently.

2024-08-12 13:17 UTC, mrwellmann commented on Source/Runtime/Components/DrillTip.cs
> +}
Currently I would rather let the user make the tip collider.
Having it auto setup with the wrong values (not the radius of the drill bit) would lead to the user searching for the issue with no hint, right?

My preferred way would be that the DrillBit creates and handles the size of the DrillTip. But this ha not to happen now.

2024-08-12 13:18 UTC, mrwellmann approved these changes

2024-08-12 13:50 UTC, merged

2024-08-12 14:05 UTC, mrwellmann commented on Source/Runtime/Components/DrillTip.cs
> +}
@VaLiuM09 you did not add the `else if (!collider.isTrigger)`

2024-08-12 14:17 UTC, VaLiuM09 commented on Source/Runtime/Components/DrillTip.cs
> +}
Sorry, missed it! Done now.